### PR TITLE
Updating the integrity value for the bootstrap

### PR DESCRIPTION
**Pull request by ageekymonk**
The integrity value for bootstrap css and js files are wrong. This is causing the browser to reject them causing the page looks bad.

## What does this PR do?
Fixing the integrity value for the js and css files of bootstrap.

## What gif best describes this PR or how it makes you feel?

https://media.giphy.com/media/hvG7cXW7DE4SQG1tzT/giphy.gif

## Completion checklist

- [x] Additions and changes have unit tests
- [x] The pull request has been appropriately labeled using the provided PR labels
- [x] GitHub actions automation is passing (`make test`, `make lint`, `make security-test`, `make test-js`)
- [x] If the UI contents or JavaScript files have been modified, generate a new example report:

```bash
# Generate the updated Javascript bundle
make build-js

# Generate the example report
make generate-report
```

### CODE REVIEW

**Comment by kmcquade** [comment]
Thanks! Can you please run the scripts to generate the updated report? make build-js and make generate-report

**Comment by ageekymonk** [comment]
> Thanks! Can you please run the scripts to generate the updated report? make build-js and make generate-report

Thanks. I have updated them.

**Comment by kmcquade** [comment]
@ageekymonk thanks for updating the report. Looks like there are merge conflicts, if you resolve them I can approve and merge

**Comment by SvenMarquardt5772** [comment]
Something went wrong in this merge. After the forcepush the change for the new hashes got deleted. The issue is still there. Here the only commit merged was a615a4dd970f5f30de971c1c9d296f9bf822832f but not c95ed8d1ac95e1680b17ffd066021c4c739fe9c8

**Comment by brendan-s1** [comment]
Can confirm this is still an issue. Is there a local workaround to get the formatting back?

**Comment by kmcquade** [comment]
@SvenMarquardt5772 @brendan-s1 - can you submit a PR with the change? Or provide an example of what to change exactly?

**Comment by brendan-s1** [comment]
Sure, there are two places in the file that mention 'Integrity' 👍 

```
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
```

Changed to:

```
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
crossorigin="anonymous">
```

And there is a second block which uses it below. Note: I'm using this in Multi-Account mode, which auto-generates the html. Not sure if single account mode has the same issue or not.

**Pull request merged**
