### PR TITLE
Ability to return json results when used as python lib

### PR DESCRIPTION
**Pull request by mrpool404**
Modified file : '/cloudsplaining/command/scan.py'
Modified Function : scan_account_authorization_details

## What does this PR do?

It allows to get json results from the scan_account_authorization_details when used as python library. It helps in programmatically using the output for further actions where writing to a file is not available.

Need to change the return type of the function as it returns json.
Added return_json_results parameter to return json only if required and the update does not break existing implementations. 
Return a json object with rendered html report string and json results if the return_json_results parameter is set as True

### CODE REVIEW

**Comment by mrpool404** [comment]
@kmcquade could you please review this ?
Also i have signed the CLA still it is flagging as cla missing.

**Comment by kmcquade** [comment]
Hey @mrpool404. Is there any reason you can't use the AuthorizationDetails object directly? See how we use it here: https://github.com/salesforce/cloudsplaining/blob/master/cloudsplaining/command/scan.py#L151-L154

**Comment by mrpool404** [comment]
Hey @kmcquade , yes it is available there, however my intent is getting both the html report and the json from a single place. One would have to fetch the json and html from different calls. In the scan_account_authorization_detail we are actually processing both of them and readily available during the same call to the function. So thought it would be helpful to get it at a single go without having to make a separate call and adding to the computation time. Also i know there is write to file option available however returning the json would help in environment where file system is not available like aws lambda.

**Comment by kmcquade** [comment]
I'd prefer to not modify this function if possible. Instead, I suggest replicating the `scan_account_authorization_details` method on your end. Something to this effect:

```python
def custom_scan_account_authorization_details(
    account_authorization_details_cfg: Dict[str, Any],
    exclusions: Exclusions,
    minimize: bool = False,
)
    authorization_details = AuthorizationDetails(
        account_authorization_details_cfg, exclusions
    )
    results = authorization_details.results

    # Lazy method to get an account ID
    account_id = ""
    for role in results.get("roles", []):
        if "arn:aws:iam::aws:" not in results["roles"][role]["arn"]:
            account_id = get_account_from_arn(results["roles"][role]["arn"])
            break
    html_report = HTMLReport(
        account_id=account_id,
        account_name=account_name,
        results=results,
        minimize=minimize,
    )
    rendered_report = html_report.get_html_report()
    return {
        "iam_results" : authorization_details.results,
        "iam_findings" : results,
        "rendered_report" : rendered_report
    }
```

**Comment by kmcquade** [comment]
@mrpool404 - can you fix the tests? Then I can merge.

**Comment by mrpool404** [comment]
@kmcquade Done !

**Comment by mrpool404** [comment]
@kmcquade could you please rerun the checks ? i think the check failed as it was unable to get the tar due to some reason.

**Comment by mrpool404** [comment]
@kmcquade, the [rerun](https://github.com/salesforce/cloudsplaining/actions/runs/1666733402) picked up a previous [commit](https://github.com/mrpool404/cloudsplaining/commit/347590e62867711de4a21c7e02208d7fe04e237e) as it is showing the same error for the return type any typo which i have updated in the latest [commit](https://github.com/mrpool404/cloudsplaining/commit/2f3fd52d0a7764dc8b30d5c1f1275387800d7418). Not sure why that's the case. I believe that the test should pass as the mypy checked passed in the previous run

**Comment by kmcquade** [comment]
@mrpool404 merged and triggered a release!

By the way - it sounds like you are running Cloudsplaining in a Lambda function - would love to see some open source contributions showing that! Feel free to ping me on Twitter [@kmcquade3](https://twitter.com/kmcquade3) or chat here if you'd like to chat more.

**Comment by mrpool404** [comment]
@kmcquade  Thanks!
Sure will try to publish it once I'm done!

**Pull request merged**
