### PR TITLE
Fixing bug in scan-policy-file command

### PR DESCRIPTION
**Pull request by saikirankv**
## What does this PR do?
#142 
[//]: # (Required: Describe the effects of your pull request in detail. If
multiple changes are involved, a bulleted list is often useful.)

## What gif best describes this PR or how it makes you feel?

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [ ] Additions and changes have unit tests
- [ ] Python Unit tests, Pylint, security testing, and Integration tests are passing.
- [ ] Javascript tests are passing (`npm test`)
- [ ] If the UI contents or JavaScript files have been modified, generate a new example report (`npm build` and `python3 ./utils/generate_example_report.py`)
- [ ] The pull request has been appropriately labeled using the provided PR labels

### CODE REVIEW

**Comment by saikirankv** [comment]
@kmcquade  can you review this PR?  PrivilegeEscalation is returning a list of dicts not a simple dict.

**Comment by kmcquade** [comment]
@saikirankv we should probably include unit tests here to verify the output.

Perhaps we can use this opportunity to include the output as JSON, which is a long-requested feature (sorry for not opening an issue on that). Then we run a unit test on that. Should be straightforward.

Let me know what you think.

**Comment by saikirankv** [comment]
yes, I can write some unittests for it. Returning output as JSON means it should return results variable at https://github.com/salesforce/cloudsplaining/blob/b895f3cf133978a2cdf670c91b4322a9361b9aab/cloudsplaining/command/scan_policy_file.py#L81

**Comment by kmcquade** [comment]
Oh, sorry, I forgot that the JSON gets returned from that function. Silly me.

I will open up a new GitHub issue to make it so we can specify JSON output as an argument to the command as well instead of printing to the console.

I'll go ahead and merge this.

**Comment by saikirankv** [comment]
@kmcquade after releasing the changes, can you inform https://github.com/salesforce/cloudsplaining/issues/142 here.

**Pull request merged**
