### PR TITLE
Bump pyyaml version to fix bug

### PR DESCRIPTION
**Pull request by forced-request**
## What does this PR do?

This PR bumps the pyyaml version to 6.0.1 to mitigate some issues that I encountered during local setup.

Ref: https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources

```
Collecting pyyaml==6.0 (from -r requirements.txt (line 11))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/john/tools/ScoutSuite/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/john/tools/ScoutSuite/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/john/tools/ScoutSuite/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/rp/dsyxds457wl18_cpnzbvwst80000gp/T/pip-build-env-kqz59wg7/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [ ] Additions and changes have unit tests
- [ ] The pull request has been appropriately labeled using the provided PR labels
- [ ] GitHub actions automation is passing (`make test`, `make lint`, `make security-test`, `make test-js`)
- [ ] If the UI contents or JavaScript files have been modified, generate a new example report:

```bash
# Generate the updated Javascript bundle
make build-js

# Generate the example report
make generate-report
```

### CODE REVIEW

**Comment by gruebel** [comment]
hey @forced-request please sign the CLA and then we are good to go 🙂

**Comment by gruebel** [comment]
@forced-request still interested in doing the change, otherwise I will do it in my open PR or a follow-up.

**Comment by forced-request** [comment]
> @forced-request still interested in doing the change, otherwise I will do it in my open PR or a follow-up.

@gruebel Interestingly enough, I did already sign the agreement. Not sure why the bot isn't updating, but here's a screenshot:

Screenshot 2023-08-23 at 8 29 16 AM

If it's easiest, feel free to just fix this in another PR :)

**Comment by gruebel** [comment]
🤔 could you try to resolve the merge conflict and push the change, maybe it will trigger the CLA bot again. I'm ok to wait some extra days. If you already took the time to create a PR for fixing, then I don't want to steal it away from you 😄

**Comment by nitrocode** [comment]
Ah this could solve a similar bug I'm seeing for both policy_sentry and cloudsplaining

https://github.com/salesforce/cloudsplaining/issues/306

**Review by nitrocode — APPROVED** [review]

**Pull request closed without merging**
