### PR TITLE
Implemented Vue router for navbar

### PR DESCRIPTION
**Pull request by rohanshenoy96**
## What does this PR do?
Added Vue router for navigation across application and created view for each page #116 
[//]: # (Required: Describe the effects of your pull request in detail. If
multiple changes are involved, a bulleted list is often useful.)

- Vue Router implementation for navigation within application
- Created Views for each page

## What gif best describes this PR or how it makes you feel?

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [x] Additions and changes have unit tests
- [x] Python Unit tests, Pylint, security testing, and Integration tests are passing.
- [x] Javascript tests are passing (`npm test`)
- [x] If the UI contents or JavaScript files have been modified, generate a new example report (`npm build` and `python3 ./utils/generate_example_report.py`)
- [x] The pull request has been appropriately labeled using the provided PR labels

### CODE REVIEW

**Comment by kmcquade** [comment]
Ahhhh!!! This is awesome. Thank you so much @rohanshenoy96. 

Can you please generate the new index.html file? The instructions are in the checklist. Then I can see what the report actually looks like.

**Comment by rohanshenoy96** [comment]
Hi @kmcquade. I'm facing some issues with jinja2 import for python 3. It's showing **Unable to import 'jinja2'** error

**Comment by kmcquade** [comment]
That's weird. Did you install dependencies and set up the virtual environment properly?

Python stuff from contributing guide:

https://cloudsplaining.readthedocs.io/en/latest/contributing/python/


Docs on generating the report from the contribution guide:
https://cloudsplaining.readthedocs.io/en/latest/contributing/report/

**Comment by rohanshenoy96** [comment]
Installing collected packages: regex, black, coverage, pyparsing, packaging, dparse, future, invoke, isort, joblib, lazy-object-proxy, tornado, livereload, lunr, mkdocs, more-itertools, tqdm, nltk, nose, pluggy, py, iniconfig, pytest, safety, wcwidth
  Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: '/Users/rshenoy/Documents/learning/Hacktoberfest2020/Rohan Fork Repo/week2/cloudsplaining/venv/bin/python3' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-install-_opu360x/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-install-_opu360x/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-record-gxu7t7k1/install-record.txt --single-version-externally-managed --compile --install-headers '/Users/rshenoy/Documents/learning/Hacktoberfest2020/Rohan Fork Repo/week2/cloudsplaining/venv/include/site/python3.8/regex'
         cwd: /private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-install-_opu360x/regex/
    Complete output (114 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14.6-x86_64-3.8
    creating build/lib.macosx-10.14.6-x86_64-3.8/regex
    copying regex_3/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/regex
    copying regex_3/regex.py -> build/lib.macosx-10.14.6-x86_64-3.8/regex
    copying regex_3/_regex_core.py -> build/lib.macosx-10.14.6-x86_64-3.8/regex
    copying regex_3/test_regex.py -> build/lib.macosx-10.14.6-x86_64-3.8/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.macosx-10.14.6-x86_64-3.8
    creating build/temp.macosx-10.14.6-x86_64-3.8/regex_3
    xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/Users/rshenoy/Documents/learning/Hacktoberfest2020/Rohan Fork Repo/week2/cloudsplaining/venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c regex_3/_regex.c -o build/temp.macosx-10.14.6-x86_64-3.8/regex_3/_regex.o
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/limits.h:63:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/limits.h:64:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    note: '__uint128_t' declared here
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from regex_3/_regex.c:48:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'xcrun' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: '/Users/rshenoy/Documents/learning/Hacktoberfest2020/Rohan Fork Repo/week2/cloudsplaining/venv/bin/python3' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-install-_opu360x/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-install-_opu360x/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jn/bmdfql6n1yz_jn8hp7klmf8r0000gp/T/pip-record-gxu7t7k1/install-record.txt --single-version-externally-managed --compile --install-headers '/Users/rshenoy/Documents/learning/Hacktoberfest2020/Rohan Fork Repo/week2/cloudsplaining/venv/include/site/python3.8/regex' Check the logs for full command output.

**Comment by rohanshenoy96** [comment]
@kmcquade It looks like some environment issue. 
# black==20.8b1
# nltk==3.5
# regex==2020.7.14
These three are crating the above error. I can run npm build but python part is not working. Any suggestions?

**Comment by rohanshenoy96** [comment]
@kmcquade. Is it possible for you to generate the index.html file. I'm having some issues on my system.

**Comment by kmcquade** [comment]
@rohanshenoy96 this is AWESOME. Thank you for your contribution!!

I was able to build out the report. I'll commit the new example report shortly.

I have three comments:
1. I noticed that the URL for "Customer Managed Policies" is called `custom-policies`, not `customer-policies`. Can you change it to `customer-policies` please? Current state is in the screenshot below
2. Notice how the URL shows a `#` in front of the `index.html#/custom-policies`. Is that intentional? `index.html/customer-policies` (without the `#`) would look much better. Or would that create issues with the computer thinking that you're referring to a file path instead?
3. Please sign the CLA, per the failing check above :) 

image

Anyway, great work. Let me know what you think about those items above.

**Comment by kmcquade** [comment]
By the way... regarding your environment issue

```
black==20.8b1
nltk==3.5
regex==2020.7.14
```

Those are all from the `requirements-dev.txt` file, not the main requirements.txt file. Perhaps you should uninstall all the packages from your virtual environment, then just install the packages from `requirements.txt` again

**Comment by rohanshenoy96** [comment]
@kmcquade.
1. I will change the url to customer-policies.
2. The hash was added by the vue router. I will check if its possible without that.
3. About the CLA, it's showing I need not sign after I updated by email to salesforce email.

**Comment by kmcquade** [comment]
@rohanshenoy96 - did you get the report to build on your machine successfully? And did you resolve that stuff in your environment?

I think we might need to move back to `index.html#/pagelink` instead of `index.html/customer-policies`. I came to this conclusion after running into issues by following these steps:

1. Pulled your updated PR
2. Ran `npm serve`. Looked fine here
3. Ran `npm build` to generate the updated `index.js` file
4. Ran `python3 ./utils/generate_example_report.py` to generate a new `index.html` file. It brought me to this:

image

Let me know if you can change the hash thing back, then we should be good to go.

**Comment by rohanshenoy96** [comment]
Hi @kmcquade 
Removed the history mode. I had similar issue in Angular for production build with #. Some config files can be used to fix that but # is easier way.

**Comment by kmcquade** [comment]
I haven't seen that before. Maybe at some point if I didn't activate my virtual environment. Idk

**Pull request merged**
